# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Users/wooka/CLionProjects/hash-octree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Users/wooka/CLionProjects/hash-octree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/wooka/CLionProjects/hash-octree/CMakeFiles /cygdrive/c/Users/wooka/CLionProjects/hash-octree/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/wooka/CLionProjects/hash-octree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hash-octree

# Build rule for target.
hash-octree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash-octree
.PHONY : hash-octree

# fast build rule for target.
hash-octree/fast:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/build
.PHONY : hash-octree/fast

#=============================================================================
# Target rules for targets named hash_octree_test

# Build rule for target.
hash_octree_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash_octree_test
.PHONY : hash_octree_test

# fast build rule for target.
hash_octree_test/fast:
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/build
.PHONY : hash_octree_test/fast

#=============================================================================
# Target rules for targets named point_data_test

# Build rule for target.
point_data_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 point_data_test
.PHONY : point_data_test

# fast build rule for target.
point_data_test/fast:
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/build
.PHONY : point_data_test/fast

src/encryptor.o: src/encryptor.cpp.o

.PHONY : src/encryptor.o

# target to build an object file
src/encryptor.cpp.o:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/encryptor.cpp.o
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/encryptor.cpp.o
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/encryptor.cpp.o
.PHONY : src/encryptor.cpp.o

src/encryptor.i: src/encryptor.cpp.i

.PHONY : src/encryptor.i

# target to preprocess a source file
src/encryptor.cpp.i:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/encryptor.cpp.i
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/encryptor.cpp.i
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/encryptor.cpp.i
.PHONY : src/encryptor.cpp.i

src/encryptor.s: src/encryptor.cpp.s

.PHONY : src/encryptor.s

# target to generate assembly for a file
src/encryptor.cpp.s:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/encryptor.cpp.s
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/encryptor.cpp.s
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/encryptor.cpp.s
.PHONY : src/encryptor.cpp.s

src/exporter.o: src/exporter.cpp.o

.PHONY : src/exporter.o

# target to build an object file
src/exporter.cpp.o:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/exporter.cpp.o
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/exporter.cpp.o
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/exporter.cpp.o
.PHONY : src/exporter.cpp.o

src/exporter.i: src/exporter.cpp.i

.PHONY : src/exporter.i

# target to preprocess a source file
src/exporter.cpp.i:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/exporter.cpp.i
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/exporter.cpp.i
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/exporter.cpp.i
.PHONY : src/exporter.cpp.i

src/exporter.s: src/exporter.cpp.s

.PHONY : src/exporter.s

# target to generate assembly for a file
src/exporter.cpp.s:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/exporter.cpp.s
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/exporter.cpp.s
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/exporter.cpp.s
.PHONY : src/exporter.cpp.s

src/hash-octree.o: src/hash-octree.cpp.o

.PHONY : src/hash-octree.o

# target to build an object file
src/hash-octree.cpp.o:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/hash-octree.cpp.o
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/hash-octree.cpp.o
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/hash-octree.cpp.o
.PHONY : src/hash-octree.cpp.o

src/hash-octree.i: src/hash-octree.cpp.i

.PHONY : src/hash-octree.i

# target to preprocess a source file
src/hash-octree.cpp.i:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/hash-octree.cpp.i
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/hash-octree.cpp.i
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/hash-octree.cpp.i
.PHONY : src/hash-octree.cpp.i

src/hash-octree.s: src/hash-octree.cpp.s

.PHONY : src/hash-octree.s

# target to generate assembly for a file
src/hash-octree.cpp.s:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/hash-octree.cpp.s
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/hash-octree.cpp.s
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/hash-octree.cpp.s
.PHONY : src/hash-octree.cpp.s

src/importer.o: src/importer.cpp.o

.PHONY : src/importer.o

# target to build an object file
src/importer.cpp.o:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/importer.cpp.o
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/importer.cpp.o
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/importer.cpp.o
.PHONY : src/importer.cpp.o

src/importer.i: src/importer.cpp.i

.PHONY : src/importer.i

# target to preprocess a source file
src/importer.cpp.i:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/importer.cpp.i
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/importer.cpp.i
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/importer.cpp.i
.PHONY : src/importer.cpp.i

src/importer.s: src/importer.cpp.s

.PHONY : src/importer.s

# target to generate assembly for a file
src/importer.cpp.s:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/importer.cpp.s
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/importer.cpp.s
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/importer.cpp.s
.PHONY : src/importer.cpp.s

src/node.o: src/node.cpp.o

.PHONY : src/node.o

# target to build an object file
src/node.cpp.o:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/node.cpp.o
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/node.cpp.o
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/node.cpp.o
.PHONY : src/node.cpp.o

src/node.i: src/node.cpp.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.cpp.i:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/node.cpp.i
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/node.cpp.i
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/node.cpp.i
.PHONY : src/node.cpp.i

src/node.s: src/node.cpp.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.cpp.s:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/node.cpp.s
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/node.cpp.s
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/node.cpp.s
.PHONY : src/node.cpp.s

src/point-data.o: src/point-data.cpp.o

.PHONY : src/point-data.o

# target to build an object file
src/point-data.cpp.o:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/point-data.cpp.o
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/point-data.cpp.o
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/point-data.cpp.o
.PHONY : src/point-data.cpp.o

src/point-data.i: src/point-data.cpp.i

.PHONY : src/point-data.i

# target to preprocess a source file
src/point-data.cpp.i:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/point-data.cpp.i
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/point-data.cpp.i
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/point-data.cpp.i
.PHONY : src/point-data.cpp.i

src/point-data.s: src/point-data.cpp.s

.PHONY : src/point-data.s

# target to generate assembly for a file
src/point-data.cpp.s:
	$(MAKE) -f CMakeFiles/hash-octree.dir/build.make CMakeFiles/hash-octree.dir/src/point-data.cpp.s
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/src/point-data.cpp.s
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/src/point-data.cpp.s
.PHONY : src/point-data.cpp.s

tests/hash-octree-test.o: tests/hash-octree-test.cpp.o

.PHONY : tests/hash-octree-test.o

# target to build an object file
tests/hash-octree-test.cpp.o:
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/tests/hash-octree-test.cpp.o
.PHONY : tests/hash-octree-test.cpp.o

tests/hash-octree-test.i: tests/hash-octree-test.cpp.i

.PHONY : tests/hash-octree-test.i

# target to preprocess a source file
tests/hash-octree-test.cpp.i:
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/tests/hash-octree-test.cpp.i
.PHONY : tests/hash-octree-test.cpp.i

tests/hash-octree-test.s: tests/hash-octree-test.cpp.s

.PHONY : tests/hash-octree-test.s

# target to generate assembly for a file
tests/hash-octree-test.cpp.s:
	$(MAKE) -f CMakeFiles/hash_octree_test.dir/build.make CMakeFiles/hash_octree_test.dir/tests/hash-octree-test.cpp.s
.PHONY : tests/hash-octree-test.cpp.s

tests/point-data-test.o: tests/point-data-test.cpp.o

.PHONY : tests/point-data-test.o

# target to build an object file
tests/point-data-test.cpp.o:
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/tests/point-data-test.cpp.o
.PHONY : tests/point-data-test.cpp.o

tests/point-data-test.i: tests/point-data-test.cpp.i

.PHONY : tests/point-data-test.i

# target to preprocess a source file
tests/point-data-test.cpp.i:
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/tests/point-data-test.cpp.i
.PHONY : tests/point-data-test.cpp.i

tests/point-data-test.s: tests/point-data-test.cpp.s

.PHONY : tests/point-data-test.s

# target to generate assembly for a file
tests/point-data-test.cpp.s:
	$(MAKE) -f CMakeFiles/point_data_test.dir/build.make CMakeFiles/point_data_test.dir/tests/point-data-test.cpp.s
.PHONY : tests/point-data-test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hash-octree"
	@echo "... rebuild_cache"
	@echo "... hash_octree_test"
	@echo "... point_data_test"
	@echo "... src/encryptor.o"
	@echo "... src/encryptor.i"
	@echo "... src/encryptor.s"
	@echo "... src/exporter.o"
	@echo "... src/exporter.i"
	@echo "... src/exporter.s"
	@echo "... src/hash-octree.o"
	@echo "... src/hash-octree.i"
	@echo "... src/hash-octree.s"
	@echo "... src/importer.o"
	@echo "... src/importer.i"
	@echo "... src/importer.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/point-data.o"
	@echo "... src/point-data.i"
	@echo "... src/point-data.s"
	@echo "... tests/hash-octree-test.o"
	@echo "... tests/hash-octree-test.i"
	@echo "... tests/hash-octree-test.s"
	@echo "... tests/point-data-test.o"
	@echo "... tests/point-data-test.i"
	@echo "... tests/point-data-test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

